#!/usr/bin/env python3

"""Installs the minimum version of all runtime dependencies, with uv.

Assumptions:
- You've installed the development dependencies: `uv sync`
- All of the dependencies in pyproject.toml are specified with `>=`
"""

import subprocess
import sys
from pathlib import Path

from packaging.requirements import Requirement

if sys.version_info >= (3, 11):
    import tomllib
else:
    import tomli as tomllib

root = Path(__file__).parents[1]
with open(root / "pyproject.toml", "rb") as f:
    pyproject = tomllib.load(f)

requirements = []
for spec in filter(bool, (s.strip() for s in pyproject["project"]["dependencies"])):
    requirement = Requirement(spec)
    if len(requirement.specifier) != 1:
        raise SystemExit(f"expected a single version specifier in {spec!r}")
    operator = next(iter(requirement.specifier)).operator
    if operator != ">=":
        raise SystemExit(f"expected `>=` in {spec!r}, found {operator!r}")
    requirements.append(spec.replace(">=", "=="))

subprocess.run(["uv", "pip", "install", "--system", *requirements], check=True)
