#!/usr/bin/env python3

"""Installs the minimum version of all dependencies, with uv.

Assumptions:
- You've installed the development dependencies: `uv pip install --system .[dev]`
- All of the dependencies in pyproject.toml are specified with `>=`
"""

import subprocess
import sys
import tomllib
from pathlib import Path

from packaging.requirements import Requirement

assert sys.version_info[0] == 3
assert sys.version_info[1] >= 10

root = Path(__file__).parents[1]
with open(root / "pyproject.toml", "rb") as f:
    pyproject_toml = tomllib.load(f)
requirements = []
for install_requires in filter(
    bool,
    (i.strip() for i in pyproject_toml["project"]["dependencies"]),
):
    requirement = Requirement(install_requires)
    assert len(requirement.specifier) == 1
    specifier = list(requirement.specifier)[0]
    assert specifier.operator == ">="
    install_requires = install_requires.replace(">=", "==")
    requirements.append(install_requires)

subprocess.run(["uv", "pip", "install", "--system", *requirements], check=True)
